#include <iostream>
#include <winsock2.h>
#include <windows.h>
#include <intrin.h>
#include <iomanip>
#include <vector>
#include <chrono>
#include <d3d9.h>
#include <tlhelp32.h>
#include <iphlpapi.h>
#include <dxgi.h>